app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

app_frontend:
    resource: "@AppBundle/Resources/config/routing_frontend/all.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /Annonce

magasin:
    resource: "@MagasinBundle/Resources/config/routing.yml"
    prefix:   /Magasin


veterinaire:
    resource: "@VeterinaireBundle/Resources/config/routing.yml"
    prefix:   /Veterinaire

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /Produit

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /evenement

animaux:
    resource: "@AnimauxBundle/Resources/config/routing.yml"
    prefix:   /Animaux


